spring.application.name=my-app

# Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/contacts_db
spring.datasource.username=postgres
spring.datasource.password=postgres