SET MODE = PostgreSQL;

CREATE TABLE contacts
(
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  TEXT NOT NULL
);


-- migration 1
ALTER TABLE contacts ADD COLUMN first_name TEXT;
ALTER TABLE contacts ADD COLUMN last_name TEXT;
ALTER TABLE contacts ADD COLUMN phone TEXT;
ALTER TABLE contacts ADD COLUMN email TEXT;
ALTER TABLE contacts
    ALTER COLUMN name DROP NOT NULL;


-- Suppose one were doing this mig in prod
-- 2. Split existing name into first_name and last_name
-- This assumes "First Last" format
-- UPDATE contacts
-- SET
--     first_name = split_part(name, ' ', 1),
--     last_name  = split_part(name, ' ', 2);
--
-- 3. Make them NOT NULL (after data is populated)
-- ALTER TABLE contacts
--     ALTER COLUMN first_name SET NOT NULL,
--     ALTER COLUMN last_name SET NOT NULL;
--
-- 4. Drop old column
-- ALTER TABLE contacts
--     DROP COLUMN name;

